CC = gcc
CFLAGS = -g -Wall -Wextra -Wpedantic -Wshadow -O2 -pthread
TARGET = url-shortener

url-shortener:	$(Target)

$(TARGET): $(TARGET).o  
	$(CC) $(CFLAGS) -o $(Target) $(TARGET).o 

$(TARGET).o: $(TARGET).cpp
	$(CC) $(CFLAGS) -c $(TARGET).cpp

clean:
	rm $(TARGET) $(TARGET).o 

help:
	@echo	"Usage: make [target] ../n"
	@echo	"Miscellaneous:"
	@echo	"help\t\t\tShows this help\n"
	@echo	"Build:"
	@echo	"all\t\t\tBuild all the project\n"
	@echo	"Cleaning:"
	@echo	"clean\t\t\tRemove all intermediate objects"
